In [21]:
import delta_sharing
CREDENTIAL = "config.share" 
client = delta_sharing.SharingClient(CREDENTIAL)
SHARE_NAME = 'amsterdam_students_share' 
directory = 'Data'

In [48]:
directory = 'Data/Equinox'
equinox_schema = "equinox_reporting" 
equinox_tables = [ "dim_priority"
                  #"fct_work_reports", 
                  #"dim_stock_type", 
                  #"dim_task", 
                  #"fct_stock_issue", 
                  #"dim_fault_code", 
                  #"dim_campaign"
                ] 
for table in equinox_tables: 
    table_name = table 
    equinox_url = f"{CREDENTIAL}#{SHARE_NAME}.{equinox_schema}.{table}" 
    table = delta_sharing.load_as_pandas(equinox_url) 
    table.to_parquet(f"{directory}/{table_name}.parquet", index=False)

In [23]:
tsf_schema = "train_service_foundation" 
tsf_tables = [ "dim_train_service", 
              "fact_passing_point", 
              "fact_actual", 
              "fact_movement_service_pathway", 
              "dim_train_movement" 
            ] 
for table in tsf_tables: 
    table_name = table 
    tsf_url = f"{CREDENTIAL}#{SHARE_NAME}.{tsf_schema}.{table}" 
    table = delta_sharing.load_as_pandas(tsf_url) 
    table.to_parquet(f"{directory}/{table_name}.parquet", index=False)

In [30]:
directory = 'Data/Maintenance_restrictions'
mnr_schema = "maintenance_and_restrictions" 
mnr_tables = [ "fct_restrictions", 
              "dim_restriction_category", 
              "fct_preventive_maintenance", 
              "dim_fleet", 
              "dim_trainset", 
              "fct_corrective_maintenance", 
              "dim_depot" 
            ]
for table in mnr_tables: 
    table_name = table 
    mnr_url = f"{CREDENTIAL}#{SHARE_NAME}.{mnr_schema}.{table}" 
    table = delta_sharing.load_as_pandas(mnr_url) 
    table.to_parquet(f"{directory}/{table_name}.parquet", index=False)

In [31]:
directory = 'Data/t15'
t15_url = f"{CREDENTIAL}#{SHARE_NAME}.t15_by_passengers_delays.fac_t15_by_passenger" 
t15_df = delta_sharing.load_as_pandas(t15_url) 
t15_df.to_parquet(f"{directory}/t15_data.parquet", index=False)

In [37]:
directory = 'Data/Prothalys'
prothalys_schema = "prothalys_ingestion" 
prothalys_tables = ["dispos", 
                    "affectation_tigre_historiques", 
                    "affectation_tigres", 
                    "butees_oes", 
                    "incident_complements", 
                    "k_remise_services", 
                    "oas_vigilances", 
                    "categ_restrictions", 
                    "restrictions", 
                    "statistique_restriction_engagements", 
                    "departs", 
                    "consequence_dispo_incompletes"
                    ]
for table in prothalys_tables: 
    table_name = table 
    prothalys_url = f"{CREDENTIAL}#{SHARE_NAME}.{prothalys_schema}.{table}" 
    table = delta_sharing.load_as_pandas(prothalys_url) 
    table.to_parquet(f"{directory}/{table_name}.parquet", index=False)

In [70]:
import pandas as pd

df = pd.read_parquet('Data/t15/t15_data.parquet')
pd.set_option('display.max_columns', None)

# Preview the data again
df.head(10)

,date_id,service_id,route_type,is_origin_flag,is_destination_flag,is_bru_passage_flag,is_passage_transborded_train_flag,passage_eurostar_code,passage_number,planned_datetime_ts,effective_datetime_ts,passage_delay_minute,is_T15_flag,is_T60_flag,is_T90_flag,is_T120_flag,is_T180_flag,compensation_liability_evouchers,compensation_liability_cash,last_passage_delay_minute,passage_imputation_minute,delay_cause_id,is_passage_cancelled_flag,service_passage_id,service_passage_order
0,20250104,9002_20250104,Channel,False,True,False,False,019649,2,2025-01-04 08:49:00,2025-01-04 08:48:00,-1.0,1,1,1,1,1,0.00,0.00,0.0,-1.0,NaN,False,9002_20250104_019649,9002_20250104_2
1,20250104,9002_20250104,Channel,True,False,False,False,022726,1,2025-01-04 06:31:00,2025-01-04 06:31:00,0.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9002_20250104_022726,9002_20250104_1
2,20250111,9002_20250111,Channel,False,True,False,False,019649,2,2025-01-11 08:53:00,2025-01-11 08:49:00,-4.0,1,1,1,1,1,0.00,0.00,-1.0,-3.0,NaN,False,9002_20250111_019649,9002_20250111_2
3,20250111,9002_20250111,Channel,True,False,False,False,022726,1,2025-01-11 06:31:00,2025-01-11 06:30:00,-1.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9002_20250111_022726,9002_20250111_1
4,20250118,9002_20250118,Channel,False,True,False,False,019649,2,2025-01-18 08:53:00,2025-01-18 08:50:00,-3.0,1,1,1,1,1,0.00,0.00,0.0,-3.0,NaN,False,9002_20250118_019649,9002_20250118_2
5,20250118,9002_20250118,Channel,True,False,False,False,022726,1,2025-01-18 06:31:00,2025-01-18 06:31:00,0.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9002_20250118_022726,9002_20250118_1
6,20250125,9002_20250125,Channel,False,True,False,False,019649,2,2025-01-25 08:49:00,2025-01-25 08:47:00,-2.0,1,1,1,1,1,0.00,0.00,0.0,-2.0,NaN,False,9002_20250125_019649,9002_20250125_2
7,20250125,9002_20250125,Channel,True,False,False,False,022726,1,2025-01-25 06:31:00,2025-01-25 06:31:00,0.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9002_20250125_022726,9002_20250125_1
8,20250201,9002_20250201,Channel,False,True,False,False,019649,2,2025-02-01 08:49:00,2025-02-01 09:26:00,37.0,0,1,1,1,1,0.00,0.00,28.0,9.0,12.0,False,9002_20250201_019649,9002_20250201_2
9,20250201,9002_20250201,Channel,True,False,False,False,022726,1,2025-02-01 06:31:00,2025-02-01 06:59:00,28.0,0,1,1,1,1,0.00,0.00,NaN,NaN,12.0,False,9002_20250201_022726,9002_20250201_1

In [39]:
import pandas as pd

df = pd.read_parquet('Data/survey_cleaned.parquet')
pd.set_option('display.max_columns', None)

# Preview the data again
df.tail(10)            # first 5 rows

,metadata_booking_date,metadata_class_of_service,metadata_class_of_service_code,metadata_coach_number,metadata_compensation_flag,metadata_currency,metadata_delay_code,metadata_delay_at_arrival,metadata_departure_date,metadata_departure_hour,metadata_destination_station,metadata_destination_station_code,metadata_disrup,metadata_origin_station,metadata_origin_station_code,metadata_price,metadata_on_board_the_train_v,metadata_overall_experience_v,metadata_q14_op,metadata_q17_op,metadata_recommendation_nps_a,metadata_assistance_service_v,metadata_q_total_duration,metadata_route,metadata_route_code,metadata_seat_number,metadata_segment,metadata_segment_code,metadata_tier_level,metadata_tier_level_code,metadata_train_number,metadata_train_type,metadata_train_type_code,metadata_trips_l12_months,metadata_end_date,metadata_start_date,question_overall_satisfaction_booking_experience,question_overall_satisfaction_wifi_onboard_the_train,question_overall_satisfaction_experience_at_departure_station,question_overall_satisfaction_journey_punctuality,question_overall_satisfaction_comfort_onboard_the_train,question_overall_satisfaction_cleanliness_onboard_the_train,question_overall_satisfaction_overall_service_from_eurostar_staff,question_overall_satisfaction_information_provided_to_you_before_travelling,question_lounge_overall_f_b_your_overall_experience_in_the_premier_lounge,question_lounge_overall_f_b_the_beverage_offering_in_the_lounge,question_lounge_overall_f_b_available_space_seating,question_lounge_overall_f_b_lounge_staff,question_lounge_overall_f_b_cocktail_bar,question_lounge_overall_f_b_newspapers_magazines,question_lounge_overall_f_b_your_welcome_arrival_at_the_lounge,question_lounge_overall_f_b_atmosphere_ambience_in_the_lounge,question_lounge_overall_f_b_furniture_and_d_cor_in_the_lounge,question_lounge_overall_f_b_information_regarding_your_train_departure,question_lounge_overall_f_b_cleanliness_of_the_lounge,question_lounge_overall_f_b_the_food_offering_in_the_lounge,question_lounge_improvement,question_onboard_catering_met_quality_of_food_in_meal_service,question_onboard_catering_met_receiving_preferred_meal_option,question_onboard_catering_met_quality_of_beverages_in_meal_service,question_onboard_catering_met_staff_hospitality_during_meal_service,question_onboard_catering_met_portion_sizes,question_onboard_catering_met_range_of_food_available_in_meal_service,question_onboard_catering_met_range_of_drinks_available_in_meal_service,question_onboard_catering_met_presentation_of_food,question_disruption_performan_the_information_available_to_you,question_disruption_performan_the_compensation_you_received_as_a_result_of_this_disruption,question_disruption_performan_frequency_regularity_of_updates,question_disruption_performan_the_accuracy_of_all_information_provided,question_disruption_performan_the_consistency_of_information_from_different_sources,question_disruption_performan_the_frequency_with_which_you_were_kept_updated,question_disruption_performan_information_provided_in_stations_e_g_from_staff_on_screens,question_disruption_performan_information_on_board_the_train_e_g_from_staff_announcements,question_disruption_performan_information_available_through_the_eurostar_website_or_app,question_disruption_performan_information_received_from_eurostar_via_e_mail_or_sms,question_disruption_performan_passenger_care_hotel_taxi_food_boxes,question_disruption_performan_eurostar_s_overall_management_of_this_disruption,question_usage_hv,question_disability_and_acces,question_assistance_service,question_assistance_service_r,question_language,question_at_the_station_checking_in_to_departures_area,question_at_the_station_boarding_the_train,question_at_the_station_toilets_washrooms_in_the_station,question_at_the_station_the_security_process_baggage_checks_and_scanners,question_at_the_station_passport_control,question_at_the_station_pre_departure_announcements_in_the_station,question_at_the_station_available_space_seating_in_the_waiting_area,question_at_the_station_the_facilities_in_the_waiting_area,question_at_the_station_the_signage_and_directions_to_your_platform_and_train,question_on_board_the_train1_the_noise_on_board,question_on_board_the_train1_the_atmosphere_on_board,question_on_board_the_train1_the_temperature_on_board,question_on_board_the_train1_the_level_of_comfort_on_board,question_on_board_the_train1_the_availability_of_toilet_facilities_on_board,question_on_board_the_train1_the_cleanliness_on_board_the_train,question_on_board_the_train1_seat_comfort,question_arrival_the_goodbye_you_received_from_train_staff_when_you_reached_your_destination,question_arrival_disembarking_the_train,question_arrival_signage_for_onward_journey_and_or_connections_at_destination_station,question_arrival_onboard_announcement_on_arrival_by_train_manager,question_staff_on_board_cleaning_staff,question_staff_on_board_train_manager,question_service_provided_by_when_getting_in_touch_via_the_contact_centre,question_service_provided_by_at_the_departure_station,question_service_provided_by_at_the_ticket_gates,question_service_provided_by_at_security_baggage_checks_scanning,question_service_provided_by_on_the_train,question_service_provided_by_train_manager,question_service_provided_by_at_the_eurostar_caf_onboard,question_service_provided_by_at_your_destination_station,question_staff_manners_staff_were_visible,question_staff_manners_staff_were_friendly_and_welcoming,question_staff_manners_staff_were_helpful,question_impact_of_cleaning_p_this_cleaning_process_is_important_to_ensure_your_comfort_on_the_train,question_impact_of_cleaning_p_this_cleaning_process_helps_to_reinforce_your_satisfaction_with_eurostar,question_impact_of_cleaning_p_this_cleaning_process_encourages_you_to_choose_eurostar_again_in_the_future,question_ticket_price_satisfa,question_overall_rating,question_reasons_for_choosing,question_future_consideration,question_strategic_pillar_ass_travelling_by_eurostar_is_an_environmentally_sustainable_option,question_strategic_pillar_ass_eurostar_manages_its_food_and_drink_offering_at_station_lounges_and_onboard_in_an_environmentally_sustainable_way,question_lounge_usage,question_hv_11,question_hv_12,question_hv_22,question_hv_21,question_hv_32,question_hv_31,question_hv_42,question_hv_41,question_residence,question_age,question_on_board_the_train2_the_cleanliness_of_toilet_facilities_on_board_the_train,question_on_board_the_train2_the_information_and_announcements_provided_on_board,question_on_board_the_train2_range_of_food_drink_available_at_the_eurostar_caf,question_on_board_the_train2_the_wi_fi_on_board,question_qid61_nps_group,question_onboard_catering_ove,question_visit_cafe,question_eurostar_cafe_your_overall_experience_at_the_eurostar_caf,question_eurostar_cafe_the_service_you_received_from_staff,question_eurostar_cafe_the_quality_of_the_food,question_eurostar_cafe_the_quality_of_the_drinks,question_eurostar_cafe_the_range_of_food_on_offer,question_eurostar_cafe_the_range_of_drinks_on_offer,question_eurostar_cafe_the_prices_value_for_money_of_food_and_drinks,question_eurostar_cafe_the_product_availabilty,question_purchase_cafe,question_connecting_journey,question_main_trip_purpose,question_leisure_reason
286358,2026-05-10T12:18:45Z,Eurostar Plus,NaN,23.0,0.0,EUR,NaN,NaN,2026-05-13T00:00:00Z,09:46,Liege-Guillemins,NaN,None,Paris Gare du Nord,NaN,94.0,None,None,None,None,8.0,None,366,Red,NaN,61.0,Mature VFR,NaN,None,NaN,9423.0,PBKA,NaN,4.0,2026-05-15T10:15:52Z,2026-05-15T10:09:45Z,Satisfied,Not applicable / can't recall,Satisfied,Dissatisfied,Satisfied,Very satisfied,Very satisfied,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No,None,<NA>,French,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Satisfied,Very satisfied,Satisfied,None,None,None,None,None,None,None,None,None,None,4,5,5,<NA>,<NA>,<NA>,4,4,['It was the quickest option'],Eurostar would be my preferred choice,4,4,None,None,None,None,None,None,None,None,None,France,Over 74 years old,None,None,None,None,Passive,None,No,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a short break
286359,2026-01-21T07:57:43Z,Eurostar Standard,NaN,5.0,0.0,EUR,NaN,2.0,2026-05-13T00:00:00Z,14:36,London St Pancras Int'l,NaN,None,Paris Gare du Nord,NaN,87.0,None,The passageways on departure and arrival were ...,None,None,7.0,None,345,Blue,NaN,51.0,None,NaN,None,NaN,9037.0,E320,NaN,1.0,2026-05-15T10:22:37Z,2026-05-15T10:16:51Z,Very satisfied,Dissatisfied,Dissatisfied,Satisfied,Satisfied,Satisfied,Satisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No,None,<NA>,English,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Not applicable/ Did not use,Not applicable/ Did not use,Satisfied,Satisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,None,Neither satisfied nor dissatisfied,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3,3,['To avoid additional transfers at my destinat...,I would consider Eurostar along with other com...,3,3,None,None,None,None,None,None,None,None,None,Another country (please select),Between 35 - 49,None,None,None,None,Passive,None,None,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a short break
286360,2026-04-16T05:44:43Z,Eurostar Premier,NaN,2.0,0.0,EUR,NaN,32.0,2026-05-13T00:00:00Z,11:58,Paris Gare du Nord,NaN,3,Rotterdam Centraal,NaN,215.0,None,None,None,None,10.0,None,434,Red,NaN,83.0,None,NaN,None,NaN,9340.0,E320,NaN,1.0,2026-05-15T10:28:04Z,2026-05-15T10:20:49Z,Very satisfied,Very satisfied,Very satisfied,Satisfied,Satisfied,Satisfied,Very satisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,Satisfied,Satisfied,Satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,None,None,None,Satisfied,Satisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Very satisfied,Very satisfied,Very satisfied,None,Satisfied,None,No,None,<NA>,Dutch,None,Very satisfied,Satisfied,None,None,Neither satisfied nor dissatisfied,None,None,Neither satisfied nor dissatisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5,5,5,4,5,1,3,4,['To avoid additional transfers at my destinat...,Eurostar would be my preferred choice,5,<NA>,None,None,None,None,None,None,None,None,None,The Netherlands,Between 50 - 64,None,None,None,None,Promoter,Very satisfied,None,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a short break
286361,2026-04-10T03:04:57Z,Eurostar Standard,NaN,15.0,0.0,EUR,NaN,39.0,2026-05-11T00:00:00Z,14:52,London St Pancras Int'l,NaN,5,Brussels Midi / Zuid,NaN,208.0,Danke für das Formular zur Weiterreichung an G...,None,None,None,10.0,None,329,Blue,NaN,85.0,Small Business,NaN,Classique,NaN,9141.0,E300,NaN,5.0,2026-05-15T10:40:24Z,2026-05-15T10:34:55Z,Very satisfied,Dissatisfied,Satisfied,Neither satisfied nor dissatisfied,Satisfied,Satisfied,Very satisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Very satisfied,Not applicable/ Did not use,Very satisfied,Satisfied,Very satisfied,Not applicable/ Did not use,Not applicable/ Did not use,None,Very satisfied,None,No,None,<NA>,German,None,None,None,None,None,None,None,None,None,Satisfied,None,Satisfied,None,Satisfied,None,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5,5,5,<NA>,<NA>,<NA>,<NA>,5,['It was the most environmentally-friendly opt...,Eurostar is the only company I would consider,5,3,None,None,None,None,None,None,None,None,None,Germany,Between 50 - 64,Satisfied,Satisfied,None,None,Promoter,None,None,None,None,None,None,None,None,None,None,None,Yes,Business,None
286362,2026-04-28T12:51:52Z,Eurostar Standard,NaN,12.0,0.0,EUR,NaN,30.0,2026-05-13T00:00:00Z,10:40,London St Pancras Int'l,NaN,4,Amsterdam Centraal,NaN,35.0,None,None,The checks in Amsterdam were a bit chaotic and...,None,8.0,None,646,Blue,NaN,67.0,None,NaN,None,NaN,9133.0,E320,NaN,1.0,2026-05-15T10:41:56Z,2026-05-15T10:31:10Z,Satisfied,Neither satisfied nor dissatisfied,Dissatisfied,Dissatisfied,Very satisfied,Satisfied,Satisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Neither satisfied nor dissatisfied,Not applicable/ Did not use,Satisfied,Dissatisfied,Dissatisfied,Not applicable/ Did not use,Neither satisfied nor dissatisfied,None,Satisfied,None,No,None,<NA>,English,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Not applicable/ Did not use,Satisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Not applicable/ Did not use,Not applicable/ Did not use,None,Not applicable/ Did not use,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,3,['It was the most environmentally-friendly opt...,I would consider Eurostar along with other com...,5,<NA>,None,None,None,None,None,None,None,None,None,Another country (please select),Between 18 - 25,None,None,None,None,Passive,None,None,None,None,None,None,None,None,None,None,None,Yes,Leisure,Travel for a main holiday
286363,2026-03-12T22:03:03Z,Eurostar Standard,NaN,13.0,0.0,USD,NaN,0.0,2026-05-10T00:00:00Z,08:16,Amsterdam Centraal,NaN,None,London St Pancras Int'l,NaN,104.0,None,None,None,None,10.0,None,350,Blue,NaN,75.0,None,NaN,Classique,NaN,9114.0,E320,NaN,1.0,2026-05-15T10:46:32Z,2026-05-15T10:40:42Z,Very satisfied,Dissatisfied,Satisfied,Very satisfied,Very satisfied,Very satisfied,Neither satisfied nor dissatisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No,None,<NA>,English,None,None,None,None,None,None,None,None,None,Satisfied,None,Satisfied,None,Satisfied,None,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4,3,3,<NA>,<NA>,<NA>,4,4,['It was the cheapest option' 'I prefer taking...,Eurostar would be my preferred choice,<NA>,<NA>,None,None,None,None,None,None,None,None,None,Another country (please select),Between 18 - 25,Satisfied,Very satisfied,None,None,Promoter,None,None,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a main holiday
286364,2026-04-26T09:23:53Z,Eurostar Standard,NaN,7.0,0.0,EUR,NaN,0.0,2026-05-11T00:00:00Z,08:17,Amsterdam Centraal,NaN,None,Paris Gare du Nord,NaN,135.0,None,Il n’y avait que 2 WC fonctionnels pour l’ense...,None,None,4.0,None,369,Red,NaN,85.0,None,NaN,None,NaN,9415.0,PBA,NaN,1.0,2026-05-15T11:02:31Z,2026-05-15T10:56:22Z,Satisfied,Very dissatisfied,Dissatisfied,Very satisfied,Dissatisfied,Dissatisfied,Not applicable / can't recall,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No,None,<NA>,French,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Satisfied,Dissatisfied,Not applicable/ Did not use,Not applicable/ Did not use,None,None,Not applicable/ Did not use,Not applicable/ Did not use,None,Not applicable/ Did not use,<NA>,<NA>,<NA>,5,5,5,3,3,['Other (please specify)'],I would not consider Eurostar,5,<NA>,None,None,None,None,None,None,None,None,None,France,Between 26 - 34,None,None,None,None,Detractor,None,None,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a main holiday
286365,2025-12-17T15:27:05Z,Eurostar Plus,NaN,3.0,0.0,USD,NaN,52.0,2026-05-10T00:00:00Z,12:18,Amsterdam Centraal,NaN,4,Paris Gare du Nord,NaN,122.0,None,I've been on other trains that offer beverages...,None,None,9.0,None,500,Red,NaN,75.0,None,NaN,Classique,NaN,9439.0,PBA,NaN,1.0,2026-05-15T11:13:23Z,2026-05-15T11:05:02Z,Neither satisfied nor dissatisfied,Very dissatisfied,Very dissatisfied,Very dissatisfied,Very dissatisfied,Neither satisfied nor dissatisfied,Very dissatisfied,Very dissatisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Satisfied,Satisfied,Satisfied,Satisfied,Satisfied,Not applicable/ Did not use,Not applicable/ Did not use,None,Satisfied,None,Yes,No,<NA>,English,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Very satisfied,Not applicable / did not use,Neither satisfied nor dissatisfied,None,None,None,None,None,None,None,None,None,None,4,5,5,4,4,4,3,5,['Quality of service'],Eurostar would be my preferred choice,<NA>,<NA>,None,None,None,None,None,None,None,None,None,USA,Between 65 - 74,None,None,None,None,Promoter,None,Yes,Satisfied,Very satisfied,Not applicable / did not use,Satisfied,Satisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Yes,Yes,Leisure,Other (please specify)
286366,2026-03-12T05:01:45Z,Eurostar Standard,NaN,7.0,0.0,EUR,NaN,NaN,2026-05-13T00:00:00Z,12:18,Brussels Midi / Zuid,NaN,None,Paris Gare du Nord,NaN,0.0,None,Siege peu propre,None,None,8.0,None,528,Red,NaN,63.0,None,NaN,Avantage,NaN,9439.0,PBA,NaN,22.0,2026-05-15T11:40:06Z,2026-05-15T11:31:17Z,Satisfied,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Dissatisfied,Dissatisfied,Dissatisfied,Neither satisfied nor dissatisfied,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No,None,<NA>,French,None,Neither satisfied nor dissatisfied,Not applicable / Can't recall,None,None,Neither satisfied nor dissatisfied,None,None,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3,3,4,<NA>,<NA>,<NA>,2,4,['It was the quickest option'],Eurostar would be my preferred choice,3,<NA>,None,None,None,None,None,None,None,None,None,France,Between 50 - 64,None,None,None,None,Passive,None,None,None,None,None,None,None,None,None,None,None,No,Visiting friends or relatives,None
286367,2026-04-18T13:02:38Z,Wheelchair Companion,NaN,14.0,0.0,GBP,NaN,1.0,2026-05-07T00:00:00Z,18:04,Amsterdam Centraal,NaN,None,London St Pancras Int'l,NaN,39.0,None,None,None,Excellent,10.0,None,641,Blue,NaN,14.0,Young Leisure,NaN,None,NaN,9152.0,E320,NaN,1.0,2026-05-15T11:45:55Z,2026-05-15T11:35:13Z,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,Yes – I booked assistance before I travelled,5,English,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Very satisfied,Neither satisfied nor dissatisfied,Very satisfied,Very satisfied,Satisfied,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5,5,5,<NA>,<NA>,<NA>,5,5,['Other (please specify)'],Eurostar is the only company I would consider,4,4,None,None,None,None,None,None,None,None,None,United Kingdom,Between 35 - 49,None,None,None,None,Promoter,None,None,None,None,None,None,None,None,None,None,None,No,Leisure,Travel for a short break

In [2]:
import pandas as pd

df = pd.read_parquet('Data/Train_service/dim_train_service.parquet')
pd.set_option('display.max_columns', None)

# Preview the data again
df.head(20)            # first 5 rows

,service_id,axis_id,an_id,date_id,train_service,trainset,diagram_id,equipment_type,travel_date_dt,service_type,route_type,train_operator,origin_point_id,origin_theoretical_time,destination_point_id,destination_theoretical_time,od,is_cancelled_flag,cancelled_date_ts,is_excluded_flag,is_always_on_time_flag,is_forced_flag
0,9123_20250430,90,NaN,20250430,9123,3212-3211,E002,E300,2025-04-30,COMMERCIAL,Channel,ES,218,2025-04-30 10:56:00+00:00,22725,2025-04-30 11:57:00+00:00,Brussels Midi / Zuid-London St Pancras Int'l,False,NaT,False,False,False
1,9474_20250906,100,NaN,20250906,9474,4302,K001,TGH,2025-09-06,COMMERCIAL,Continental,ER,7666,2025-09-06 16:44:00+00:00,19648,2025-09-06 20:15:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
2,9435_20250220,103,NaN,20250220,9435,4346,K002,TGH,2025-02-20,COMMERCIAL,Continental,ER,19648,2025-02-20 11:53:00+00:00,4581,2025-02-20 16:16:00+00:00,Paris Gare du Nord-Essen Hbf,False,NaT,False,False,False
3,9438_20250929,100,NaN,20250929,9438,4342,K001,RUB,2025-09-29,COMMERCIAL,Continental,ER,7666,2025-09-29 10:44:00+00:00,19648,2025-09-29 14:09:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
4,9426_20260208,100,NaN,20260208,9426,4322,K012,RUB,2026-02-08,COMMERCIAL,Continental,ER,7666,2026-02-08 08:39:00+00:00,19648,2026-02-08 12:08:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
5,9474_20250425,100,NaN,20250425,9474,4332,K006,TGH,2025-04-25,COMMERCIAL,Continental,ER,7666,2025-04-25 16:44:00+00:00,19648,2025-04-25 20:05:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
6,9435_20251130,99,NaN,20251130,9435,4306,K005,RUB,2025-11-30,COMMERCIAL,Continental,ER,19648,2025-11-30 11:51:00+00:00,7666,2025-11-30 15:15:00+00:00,Paris Gare du Nord-Cologne Hbf,False,NaT,False,False,False
7,9447_20250329,99,NaN,20250329,9447,4307,K001,TGH,2025-03-29,COMMERCIAL,Continental,ER,19648,2025-03-29 13:52:00+00:00,7666,2025-03-29 17:15:00+00:00,Paris Gare du Nord-Cologne Hbf,False,NaT,False,False,False
8,9447_20250222,99,NaN,20250222,9447,4332,K003,TGH,2025-02-22,COMMERCIAL,Continental,ER,19648,2025-02-22 13:55:00+00:00,7666,2025-02-22 17:25:00+00:00,Paris Gare du Nord-Cologne Hbf,False,NaT,False,False,False
9,9435_20251106,99,NaN,20251106,9435,4342,K008,RUB,2025-11-06,COMMERCIAL,Continental,ER,19648,2025-11-06 11:51:00+00:00,7666,2025-11-06 15:15:00+00:00,Paris Gare du Nord-Cologne Hbf,False,NaT,False,False,False
10,9438_20260223,100,NaN,20260223,9438,4303,K011,RUB,2026-02-23,COMMERCIAL,Continental,ER,7666,2026-02-23 10:39:00+00:00,19648,2026-02-23 14:09:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
11,9438_20260420,100,NaN,20260420,9438,4301,K011,RUB,2026-04-20,COMMERCIAL,Continental,ER,7666,2026-04-20 10:39:00+00:00,19648,2026-04-20 14:10:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
12,9474_20250228,100,NaN,20250228,9474,4344,K006,TGH,2025-02-28,COMMERCIAL,Continental,ER,7666,2025-02-28 16:44:00+00:00,19648,2025-02-28 20:05:00+00:00,Cologne Hbf-Paris Gare du Nord,False,NaT,False,False,False
13,9435_20260224,99,NaN,20260224,9435,4304,K012,RUB,2026-02-24,COMMERCIAL,Continental,ER,19648,2026-02-24 11:51:00+00:00,7666,2026-02-24 15:14:00+00:00,Paris Gare du Nord-Cologne Hbf,False,NaT,False,False,False
14,9456_20250202,88,NaN,20250202,9456,4321,K006,TGH,2025-02-02,COMMERCIAL,Continental,ER,218,2025-02-02 15:43:00+00:00,19648,2025-02-02 17:05:00+00:00,Brussels Midi / Zuid-Paris Gare du Nord,False,NaT,False,False,False
15,9335_20251212,87,NaN,20251212,9335,4321,K012,TGH,2025-12-12,COMMERCIAL,Continental,ER,19648,2025-12-12 11:51:00+00:00,218,2025-12-12 13:17:00+00:00,Paris Gare du Nord-Brussels Midi / Zuid,False,NaT,False,False,False
16,9456_20250410,88,NaN,20250410,9456,4332,K004,TGH,2025-04-10,COMMERCIAL,Continental,ER,218,2025-04-10 15:43:00+00:00,19648,2025-04-10 17:05:00+00:00,Brussels Midi / Zuid-Paris Gare du Nord,False,NaT,False,False,False
17,9356_20250928,88,NaN,20250928,9356,4305,K013,TGH,2025-09-28,COMMERCIAL,Continental,ER,218,2025-09-28 15:44:00+00:00,19648,2025-09-28 17:08:00+00:00,Brussels Midi / Zuid-Paris Gare du Nord,False,NaT,False,False,False
18,9304_20260213,88,NaN,20260213,9304,4321,K005,TGH,2026-02-13,COMMERCIAL,Continental,ER,218,2026-02-13 07:09:00+00:00,19648,2026-02-13 08:36:00+00:00,Brussels Midi / Zuid-Paris Gare du Nord,False,NaT,False,False,False
19,9356_20260406,88,NaN,20260406,9356,4303,K008,TGH,2026-04-06,COMMERCIAL,Continental,ER,218,2026-04-06 15:42:00+00:00,19648,2026-04-06 17:10:00+00:00,Brussels Midi / Zuid-Paris Gare du Nord,False,NaT,False,False,False

In [83]:
import pandas as pd

df = pd.read_parquet('Data/t15/t15_data.parquet')
pd.set_option('display.max_columns', None)

# Preview the data again
df.tail(20)            # first 5 rows

,date_id,service_id,route_type,is_origin_flag,is_destination_flag,is_bru_passage_flag,is_passage_transborded_train_flag,passage_eurostar_code,passage_number,planned_datetime_ts,effective_datetime_ts,passage_delay_minute,is_T15_flag,is_T60_flag,is_T90_flag,is_T120_flag,is_T180_flag,compensation_liability_evouchers,compensation_liability_cash,last_passage_delay_minute,passage_imputation_minute,delay_cause_id,is_passage_cancelled_flag,service_passage_id,service_passage_order
195885,20260510,9977_20260510,Continental,False,False,False,False,000118,4,2026-05-10 18:57:00,2026-05-10 19:29:00,32.0,0,1,1,1,1,0.00,0.00,28.0,4.0,NaN,False,9977_20260510_000118,9977_20260510_4
195886,20260510,9977_20260510,Continental,False,False,True,False,000218,3,2026-05-10 18:14:00,2026-05-10 18:42:00,28.0,0,1,1,1,1,0.00,0.00,4.0,24.0,NaN,False,9977_20260510_000218,9977_20260510_3
195887,20260510,9977_20260510,Continental,True,False,False,False,018452,1,2026-05-10 16:40:00,2026-05-10 16:43:00,3.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9977_20260510_018452,9977_20260510_1
195888,20260510,9977_20260510,Continental,False,False,False,False,020516,2,2026-05-10 16:51:00,2026-05-10 16:55:00,4.0,1,1,1,1,1,0.00,0.00,3.0,1.0,NaN,False,9977_20260510_020516,9977_20260510_2
195889,20260510,9977_20260510,Continental,False,True,False,False,022784,7,2026-05-10 20:20:00,2026-05-10 20:55:00,35.0,0,1,1,1,1,0.00,0.00,29.0,6.0,NaN,False,9977_20260510_022784,9977_20260510_7
195890,20260510,9977_20260510,Continental,False,False,False,False,023316,5,2026-05-10 19:32:00,2026-05-10 20:02:00,30.0,0,1,1,1,1,0.00,0.00,32.0,-2.0,29.0,False,9977_20260510_023316,9977_20260510_5
195891,20260510,9977_20260510,Continental,False,False,False,False,023332,6,2026-05-10 20:03:00,2026-05-10 20:32:00,29.0,0,1,1,1,1,0.00,0.00,30.0,-1.0,29.0,False,9977_20260510_023332,9977_20260510_6
195892,20260517,9977_20260517,Continental,False,False,False,False,000118,4,2026-05-17 19:05:00,2026-05-17 19:05:00,0.0,1,1,1,1,1,0.00,0.00,0.0,0.0,NaN,False,9977_20260517_000118,9977_20260517_4
195893,20260517,9977_20260517,Continental,False,False,True,False,000218,3,2026-05-17 18:14:00,2026-05-17 18:14:00,0.0,1,1,1,1,1,0.00,0.00,0.0,0.0,NaN,False,9977_20260517_000218,9977_20260517_3
195894,20260517,9977_20260517,Continental,True,False,False,False,018452,1,2026-05-17 16:40:00,2026-05-17 16:40:00,0.0,1,1,1,1,1,0.00,0.00,NaN,NaN,NaN,False,9977_20260517_018452,9977_20260517_1
195895,20260517,9977_20260517,Continental,False,False,False,False,020516,2,2026-05-17 16:51:00,2026-05-17 16:51:00,0.0,1,1,1,1,1,0.00,0.00,0.0,0.0,NaN,False,9977_20260517_020516,9977_20260517_2
195896,20260517,9977_20260517,Continental,False,True,False,False,022784,6,2026-05-17 20:20:00,2026-05-17 20:22:00,2.0,1,1,1,1,1,0.00,0.00,0.0,2.0,NaN,False,9977_20260517_022784,9977_20260517_6
195897,20260517,9977_20260517,Continental,False,False,False,False,023332,5,2026-05-17 20:03:00,2026-05-17 20:03:00,0.0,1,1,1,1,1,0.00,0.00,0.0,0.0,NaN,False,9977_20260517_023332,9977_20260517_5
195898,20260524,9977_20260524,Continental,False,False,False,False,000118,4,2026-05-24 18:57:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_000118,9977_20260524_4
195899,20260524,9977_20260524,Continental,False,False,True,False,000218,3,2026-05-24 18:14:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_000218,9977_20260524_3
195900,20260524,9977_20260524,Continental,True,False,False,False,018452,1,2026-05-24 16:40:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_018452,9977_20260524_1
195901,20260524,9977_20260524,Continental,False,False,False,False,020516,2,2026-05-24 16:51:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_020516,9977_20260524_2
195902,20260524,9977_20260524,Continental,False,True,False,False,022784,7,2026-05-24 20:20:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_022784,9977_20260524_7
195903,20260524,9977_20260524,Continental,False,False,False,False,023316,5,2026-05-24 19:32:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_023316,9977_20260524_5
195904,20260524,9977_20260524,Continental,False,False,False,False,023332,6,2026-05-24 20:03:00,NaT,NaN,0,0,0,0,0,0.00,0.00,NaN,NaN,NaN,True,9977_20260524_023332,9977_20260524_6

In [25]:
df.isnull().sum()

service_id                          0
axis_id                             0
an_id                           91470
date_id                             0
train_service                       0
trainset                        39281
diagram_id                      16107
equipment_type                    139
travel_date_dt                      0
service_type                        0
route_type                          0
train_operator                      0
origin_point_id                     0
origin_theoretical_time             0
destination_point_id                0
destination_theoretical_time        0
od                                  0
is_cancelled_flag                   0
cancelled_date_ts               89808
is_excluded_flag                    0
is_always_on_time_flag              0
is_forced_flag                      0
dtype: int64